.prettierrc, eslint.config.js, package-lock.json, package.json
- 린트 추가 설정
- 빠졌던 prettier 파일 추가
- prettier 추가로 인한 패키지 1개 추가
---
- 리뷰 마감 요청일: **2025.07.21까지 리뷰 부탁드립니다.**
---
---
- 주요 구현/수정 내용:
---
---
---
=> chore: 설정 추가 (ESLint, Prettier, 패키지 설치)

.github/workflows/deploy.yml
- AWS CI/CD를 위한 yml 작성
- 외부에서 AWS 접근을 위한 IAM 키 발급
- develop에 merge 될 시 CI/CD가 돌아가며 AWS에 자동으로 배포가 진행이 됨
---
- 리뷰 마감 요청일: **2025.07.22까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `.github/workflows/deploy.yml`
- 주요 구현/수정 내용:
- CI/CD
- merge 시 자동 배포
---
---
---
#3
=> feat: AWS CI/CD (#3)

tsconfig.app.json, vite.config.ts
- vite.config 내부 resolve, alias 추가
- tsconfig.app 파일 내부 path 설정
- 절대 경로 설정
- tsconfig.app 파일 수정
- vite.config 파일 수정
---
- 리뷰 마감 요청일: **2025.07.24까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `예:tsconfig.app.json, vite.config.ts`
- 주요 구현/수정 내용:
- 절대경로 추가
---
---
---
=> chore: 절대 경로 설정 (#11)

package-lock.json, package.json, src/App.tsx
- lint 오류 수정
---
- 리뷰 마감 요청일: **2025.07.24까지 리뷰 부탁드립니다.**
---
---
- 주요 구현/수정 내용:
---
---
---
=> chore: lint 설정 (#16)

src/components/common/Header.tsx
- 불필요한 cn 유틸 제거
- 누락 되었던 cn utill 제거 완료
---
- 리뷰 마감 요청일: **2025.07.25까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `Header.tsx`
- 주요 구현/수정 내용:
- 누락 되었던 cn utill 제거
---
---
---
=> style: 공통 컴포넌트(Header) 스타일 수정 (#24)

src/components/common/Label.tsx
-  메인페이지, 패키지페이지에서 사용하는 라벨
- subtitle에서 줄바꿈이 필요한 경우가 있어서, 타입을 reactnode로 설정
---
- 리뷰 마감 요청일: 2025.07.25까지 부탁 드립니다.
---
---
- 변경된 파일: `Label.tsx`
- 주요 구현/수정 내용:
- 라벨 파일 생성
---
---
---
=> feat: 공통 라벨 컴포넌트 생성(#22)

src/components/common/Button.tsx
- 버튼 컴포넌트 중복 import 개선
---
- 리뷰 마감 요청일: **2025.07.25까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `src/components/Button.tsx`
- 주요 구현/수정 내용:
- - 버튼 컴포넌트 중복 import 개선
=> fix: 버튼 컴포넌트 중복 import 개선(#27)

src/components/common/Button.tsx
- 버튼 태그에 속성 추가
---
- 리뷰 마감 요청일: **2025.07.27까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `: src/components/Button.tsx`
- 주요 구현/수정 내용:
- 버튼 태그에 type = 'button' 속성 추가
=> fix: 버튼 컴포넌트 버튼 태그 속성 추가(#36)

package-lock.json, package.json, src/vite-env.d.ts, vite.config.ts
-  기존 `<img src="..."/>` 방식으로 사용된 SVG 아이콘은 색상, 크기, hover 등 상태에 따른 스타일링 어려움
- `svgr` 라이브러리를 도입하여 SVG 파일을 React 컴포넌트 형태로 사용하여 동적인 스타일링 가능
---
- 리뷰 마감 요청일: **2025.07.28까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `package.json`
- 주요 구현/수정 내용:
- vite-plugin-svgr 라이브러리 설치
- 변경된 파일: `vite.config.ts`
- 주요 구현/수정 내용:
- svgr 플러그인 적용
- 변경된 파일: `src/vite-env.d.ts`
- 주요 구현/수정 내용:
- 타입 지원을 위해 svgr 타입 참조 추가
---
---
---
- 해당 PR 병합 이후 아이콘은 모두 `svgr` 방식으로 컴포넌트화하여 사용해 주세요. (로고, 배경 이미지 등은 예외로 `<img>` 방식 유지)
- 기존 `<img>`로 사용된 아이콘은 별도 브랜치에서 리팩토링하겠습니다.
- 기존 svg import 방식에서 경로 끝에 `?react` 만 추가해주시면 …
=> feat: svgr 도입 (#38)

src/components/common/Icon.tsx
- SVG 아이콘을 일관된 방식으로 렌더링할 수 있도록 공통 아이콘 컴포넌트 구현
- `size`, `color`, `cursor` 등 스타일 속성 wrapper에 적용
- `fill="currentColor"` 방식의 SVG 아이콘 color 연동 가능
- `aria-label` 유무에 따라 접근성 속성(role, aria-hidden) 자동 처리
- 추가 SVGProps 확장 지원
---
- 리뷰 마감 요청일: **2025.07.28까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `src/components/common/Icon.tsx`
- 주요 구현/수정 내용:
- `size`, `color`, `cursor` 등의 스타일 속성 wrapper에 적용
- `fill="currentColor"`로 작성된 SVG 아이콘에 color 연동
- `cursor-pointer` 조건부 적용
- `ariaLabel` 유무에 따라 `role`, `aria-hidden` 자동 처리
- ...rest를 넘겨서 유연하게 SVG 기본 속성 전달 가능
---
---
---
- 공통 아이콘 컴포넌트 사용하여 아이콘 적용해주시면 됩니다.
- `icon`
- 렌더링할 SVG 컴포넌트
- `size` 
- svg를 감싸주는 div 사이즈 …
=> feat: 공통 컴포넌트(Icon) 구현 (#40)

src/components/common/Header.tsx, src/components/common/Modal.tsx
- 기존 아이콘 공통 아이콘 컴포넌트(svgr)로 교체
---
- 리뷰 마감 요청일: **2025.07.28까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `src/components/common/Header.tsx`
- 주요 구현/수정 내용:
- USER_ICONS 객체의 src 키를 -> icon으로 변경 (svg가 컴포넌트 형태로 사용 중이라 src는 의미적으로 맞지 않아 변경)
- img 태그 -> Icon 컴포넌트로 교체
- 변경된 파일: `src/components/common/Modal.tsx`
- 주요 구현/수정 내용:
- img 태그 -> Icon 컴포넌트로 교체
- alt 값 대신 버튼에 aria-label 속성 추가
---
---
---
=> refactor: 기존 아이콘 공통 아이콘 컴포넌트(svgr)로 교체 (#42)

src/components/item-row/list-component/CartItemRow.tsx
- 기존 img 태그를 사용하여 svg 파일을 가져왔던 것을 Icon 공통 컴포넌트로 변경
- 기존 img로 이미지 렌더링을 하고 있던 부분을 수정
- 추가된 Icon 공통 컴포넌트를 사용하여 변경
---
- 리뷰 마감 요청일: **2025.07.29까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `CartItemRow.tsx`
- 주요 구현/수정 내용:
- 기존 svg 파일을 img에서 사용 -> Icon 공통 컴포넌트를 사용하여 수정
---
---
---
=> refactor: 공통 컴포넌트(ItemRow) 공통 아이콘 컴포넌트(svgr)로 교체 (#44)

src/components/item-row/ItemRowLabel.tsx, src/components/item-row/ItemRowList.tsx, src/components/item-row/list-component/CartItemRow.tsx, src/components/item-row/list-component/OrderItemRow.tsx, src/components/item-row/list-component/TastingItemRow.tsx, src/types/ItemRow/itemRows.ts
- div에 role button 사용하고 있던 것을 button으로 변경
- button 내부에 aria-label 추가하여 접근성 개선
- Icon에 들어있던 flex, justify-center, items-center 제거
---
- 리뷰 마감 요청일: **2025.07.28까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `CartItemRow.tsx`
- 주요 구현/수정 내용:
- div를 사용하여 기존 버튼을 만들었는데 button으로 수정 후 aria-label 사용하여 접근성 개선
- Icon에 지정되어 겹치는 css 제거
- 변경된 파일: `ItemRowLabel.tsx`
- 주요 구현/수정 내용:
- 기존 구조인 tr th에서 div로 변경
- 변경된 파일: `CartItemRow.tsx`, `OrderItemRow.tsx`, `TastingItemRow.tsx`
- 주요 구현/수정 내용:
- 기존 구조인 tr th에서 div로 변경
---
---
---
=> refactor: CartItemRow 수량 조절 버튼 구조 변경 및 접근성 개선 및 변경된 디자인 UI 수정 (#46)

src/App.tsx, src/components/common/Header.tsx
- 기존 hover와 group을 묶어서 사용했던 메뉴를 외부로 분리
- cart Route 추가
---
- 리뷰 마감 요청일: **2025.07.30까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `App.tsx`
- 주요 구현/수정 내용:
- 라우트 수정 (mypage, cart 추가)
- 변경된 파일: `Header.tsx`
- 주요 구현/수정 내용:
- 새로운 디자인에 맞는 UI 수정
- hover group -> 각 각의 UI로 분리
---
---
---
=> refactor: 공통 컴포넌트(Header) UI 분리 (#51)

src/assets/icons/pagination/next.svg, src/assets/icons/pagination/prev.svg, src/components/common/Pagination.tsx, src/hooks/usePagination.ts
- Pagination 컴포넌트 
- 페이지 총 개수, 현재 페이지 상태, 페이지 전환 함수 받아 페이지 버튼 렌더링
- 이전/다음 버튼 비활성화 조건 처리
- 현재 페이지에 따라 버튼 상태 및 색상 다르게 표시
- 시맨틱 마크업과 접근성 고려한 aria-label 및 aria-current 적용
- usePagination 커스텀 훅
- items 배열과 pageSize를 기준으로 현재 페이지 데이터 추출
- 페이지 총 개수 계산 및 유효하지 않은 페이지 접근 시 보정
- handlePageChange를 통해 외부에서 페이지 전환 가능
---
- 리뷰 마감 요청일: **2025.07.29까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `src/components/common/Pagination.tsx`
- 주요 구현/수정 내용:
- 이전/다음 버튼 비활성화 조건 처리
- currentPage 상태에 따른 이전/다음 및 페이지 번호 버튼 스타일 조건 처리
- 페이지 수가 1개 이하일 경우 렌더링 막음
- 변경된 파일: `src/hooks/usePagination.ts`
- 주요 구현/수정 내용:
- `currentPage`: 현재 페이지 상태 관리
- `totalPages`: `items`, `pageSize` 기반으로 페이지 총 개수 계산
- `paginatedData`: 현재 페이지에 해당하는 데이터 추출
- `handlePageChange`: 페이지 전환 함수. 페이지가 유효 범위를 …
=> feat: 공통 컴포넌트(Pagination) 구현 (#35)

src/components/common/Footer.tsx
- 함수 이름 변경, export 이름 변경
---
- 리뷰 마감 요청일: **2025.07.30까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `src/components/Footer.tsx`
- 주요 구현/수정 내용:
- - 함수 이름 변경, export 이름 변경
=> fix: footer 수정 (#49)

src/components/common/Input.tsx
- 고정 너비 삭제
---
- 리뷰 마감 요청일: **2025.07.30까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `예: Input.tsx`
- 주요 구현/수정 내용:
- 고정 너비 지정돼있는 <div> 삭제
- useId() 사용
---
---
---
=> fix: 코드 수정 (#69)

src/components/common/Card.tsx, src/types/cardProps.ts
-  메인 페이지, 검색 페이지에서 보이는 카드 컴포넌트 디자인을 (이미지, 제품 이름, subtitle, 가격) 으로 우선 통일
-  코드 분리가 어려운 만큼, 코드를 조금 간결하게 수정 하였습니다.
---
- 리뷰 마감 요청일: 2025.07.31까지 부탁 드립니다.
---
---
- 변경된 파일: `src/components/common/Card.tsx`
- 주요 구현/수정 내용:
- 가격 파트 추가 
- 코드 간결하게 개선
- 변경된 파일: `src/types/cardProps.ts`
- 주요 구현/수정 내용:
- 가격 타입 정의
---
---
> 코드를 이미 벌써 사용하고 계셔서, 코드 분리 리팩토링은 하지 못했습니다. 
---
> 추후 디자인 추가 등 (제품 상세 정보 확인용)이 필요합니다.
=> feat: 카드 컴포넌트 디자인 통일 (#61)

index.html, src/App.css
- CDN 방식으로 Pretendard 웹폰트 적용
- 다이나믹 서브셋 방식 사용 (웹폰트 용량 문제 해결하기 위한 방법으로 페이지에 포함된 글자만 선택적으로 다운로드해 보다 빠르게 Pretendard 사용)
- 기본 폰트를 Pretendard로 설정 
- 
---
- 리뷰 마감 요청일: **2025.07.31까지 리뷰 부탁드립니다.**
---
---
- 주요 구현/수정 내용:
---
---
---
[Pretendard 공식 GitHub](https://github.com/orioncactus/pretendard)
=> feat: Pretendard 웹폰트 설정 (#75)

src/components/layout/Footer.tsx
- useLocation 훅을 사용하여 현재 페이지를 확인하고, 해당 페이지에 따라 플로팅 방식 변경
- z-index 값을 조정하여 푸터가 콘텐츠를 가리지 않도록 수정
---
- 리뷰 마감 요청일: **2025.08.04까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `src/components/Layout/Footer.tsx`
- 주요 구현/수정 내용:
- useLocation 훅을 사용하여 현재 페이지를 확인하고, 해당 페이지에 따라 플로팅 방식 변경
- z-index 값을 조정하여 푸터가 콘텐츠를 가리지 않도록 수정
-
=> fix: 푸터 페이지 별 플로팅 방식 수정 (#85)

src/App.tsx, src/api/auth.ts, src/components/RequireAuth.tsx, src/components/layout/Header.tsx, src/constants/apiPaths.ts, src/hooks/useSocialLogin.ts, src/mocks/handlers/auth/authHandlers.ts, src/pages/auth/Login.tsx, src/pages/auth/SocialCallback.tsx, src/stores/authStore.ts, src/types/auth.ts
- 소셜 로그인 state MSW 연동 및 관련 로직 리팩토링
- 로그인 상태 전역으로 관리
- 로그인 성공 시 상태 업데이트
- 앱 첫 진입 시 자동 로그인 처리
- 로그인 상태에 따라 라우팅 분기 및 UI 렌더링 처리
- 로그인 필요 페이지 접근 시 로그인 상태 검사 후 로그인 페이지로 리다이렉트
---
- 리뷰 마감 요청일: **2025.08.11까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `src/stores/authStore.ts`
- 주요 구현/수정 내용:
- 로그인 상태 Zustand로 전역 관리
- 로그인 상태 업데이트 및 로그아웃 시 토큰 제거 로직 구현
- 변경된 파일: `src/components/layout/Header.tsx`
- 주요 구현/수정 내용:
-  로그인 상태에 따른 UI 조건부 렌더링 적용
- 변경된 파일: `src/components/RequireAuth.tsx`
- 주요 구현/수정 내용:
-  로그인 필요 페이지 접근 시 로그인 상태 검사 후 로그인 페이지로 리다이렉트
- redirect 쿼리 파라미터 추가
- 변경된 파일: `src/App.tsx`
- 주요 구현/수정 내용:
-  앱 첫 진입 시 로그인 상태 업데이트
- 로그인 필요 페이지 `<RequireAuth>` 적용
- 변경된 파일: `src/pages/auth/Login.tsx`
- 주요 구현/수정 내용:
- 로그인 페이지 로직을 커스텀 훅(`useSocailLoginURL`)으로 분리 …
=> feat: 로그인 상태 전역 관리 (#107)

.github/workflows/deploy.yml
- VITE_API_BASE_URL -> VITE_API_URL로 변경
- github secrets에 VITE_API_URL 추가
---
- 리뷰 마감 요청일: **2025.08.14까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `.github/workflows/deploy.yml`
- 주요 구현/수정 내용:
- VITE_API_BASE_URL -> VITE_API_URL로 변경
---
---
---
=> chore: deploy script 수정 (#132)

src/constants/apiPaths.ts, src/constants/detailPage.ts, src/hooks/home/usePackagePageData.ts, src/mocks/handlers/product/product.ts, src/pages/Package.tsx
- 잘못된 엔드 포인트 수정
- 잘못 넣은 % 제거
---
- 리뷰 마감 요청일: **2025.08.16까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `src/constants/apiPaths.ts`
- 주요 구현/수정 내용:
- api 경로 추가로 인한 엔드 포인트 수정
- 변경된 파일: `src/constants/detailPage.ts`
- 주요 구현/수정 내용:
- 잘못 넣은 % 제거
- 변경된 파일: `src/hooks/home/usePackagePageData.ts`
- 주요 구현/수정 내용:
- 잘못 넣은 엔드포인트 수정
- 변경된 파일: `src/hooks/home/usePackagePageData.ts`, `src/pages/Package.tsx`
- 주요 구현/수정 내용:
- 잘못 넣은 엔드포인트 수정
---
---
---
=> refactor: detail page (#143)

src/api/productApi.ts, src/components/detail/DetailProduct.tsx, src/constants/apiPaths.ts, src/constants/message.ts, src/hooks/home/useProduct.ts, src/hooks/useDetailPage.ts, src/pages/Detail.tsx
- 장바구니 추가 api 구현
- 구매하기 api (장바구니로 우선 적용 구매 페이지가 따로 없어서)
- 일부 api request body 하드 코딩
---
- 리뷰 마감 요청일: **2025.08.17까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `src/hooks/useDetailPage.ts`
- 주요 구현/수정 내용:
- 비즈니스 로직 분리
- 변경된 파일: `src/hooks/home/useProduct.ts`, `src/constants/apiPaths.ts`, `src/api/productApi.ts`
- 주요 구현/수정 내용:
- api 호출을 위한 로직
- 스토어 id 및 생성 일자는 우선 하드 코딩
- 변경된 파일: `src/components/detail/DetailProduct.tsx`
- 주요 구현/수정 내용:
- 장바구니 추가의 경우 cart로 post 요청만 보내지게 설정
- 구매하기의 경우 cart로 post 요청 후 navigate를 사용하여 /cart로 이동 할 수 있게 설정
---
---
---
> 아직 스토어 등록이 안되어 있는 상태라 오류 발생 중
> id 값 1번 가진 스토어 만들어 달라고 back에 요청 한 …
=> feat: 상세페이지 post api 구현 (#145)

src/constants/apiPaths.ts, src/hooks/useOrder.ts, src/types/orderType.ts
- api 엔드포인트 변경
- 바디값 변경으로 인한 데이터 가공 수정
- 타입 추가
---
- 리뷰 마감 요청일: **2025.08.19까지 리뷰 부탁드립니다.**
---
---
- 변경된 파일: `src/constants/apiPaths.ts`
- 주요 구현/수정 내용:
- 엔드포인트 수정
- 변경된 파일: `src/hooks/useOrder.ts`
- 주요 구현/수정 내용:
- 변경된 바디 값에 대한 데이터 가공
- 변경된 파일: `src/types/orderType.ts`
- 주요 구현/수정 내용:
- 변경된 데이터 값에 따른 타입 수정
---
---
---
=> fix: order api 수정 (#164)

src/components/ItemRow/ListComponent/OrderItemRow.tsx, src/components/package-page/RecommendedPackageSection.tsx, src/pages/my-page/TastingReviewModal.tsx
- 전역으로 관리하고 있는 프로필을 가져와 사용
- 후기 모달에서 사용자 닉네임을 사용
- 패키지 페이지에서 사용자 닉네임을 사용
---
- 리뷰 마감 요청일: **2025.08.20까지 리뷰 부탁드립니다.**
---
---
- 주요 구현/수정 내용:
---
---
---
=> feat: 패키지 페이지, 후기 모달 닉네임 추가 (#184)

src/components/common/cards/BestReviewCard.tsx, src/components/common/cards/ReviewCard.tsx
- 모달 높이 스크롤 수정
- 무엇을 수정했는지, 어떤 문제를 해결했는지
- 코드나 로직 구조가 어떻게 변경되었는지
- 사용자나 동작에 어떤 영향이 있는지
---
- 리뷰 마감 요청일: **YYYY.MM.DD까지 리뷰 부탁드립니다.**
---
---
- 주요 구현/수정 내용:
---
---
---
=> fix: 모달 수정 (#186)

src/pages/auth/Login.tsx
Please enter the commit message for your changes. Lines starting
- 무엇을 수정했는지, 어떤 문제를 해결했는지
- 코드나 로직 구조가 어떻게 변경되었는지
- 사용자나 동작에 어떤 영향이 있는지
---
- 리뷰 마감 요청일: **YYYY.MM.DD까지 리뷰 부탁드립니다.**
---
---
- 주요 구현/수정 내용:
---
---
---
=> design: 계정 찾기 UI 제거 (#196)

src/constants/message.ts, src/hooks/user/useUser.ts, src/pages/my-page/AccountEdit.tsx
- 무엇을 수정했는지, 어떤 문제를 해결했는지
- 코드나 로직 구조가 어떻게 변경되었는지
- 사용자나 동작에 어떤 영향이 있는지
---
- 리뷰 마감 요청일: **YYYY.MM.DD까지 리뷰 부탁드립니다.**
---
---
- 주요 구현/수정 내용:
---
---
---
=> design: 회원 정보 수정 페이지 UI 수정 (#199)

.github/workflows/deploy.yml
- deploy.yml에 VITE_KAKAO_APP_KEY 추가
---
- 리뷰 마감 요청일: **2025.08.21까지 리뷰 부탁드립니다.**
---
---
- 주요 구현/수정 내용:
---
---
---
=> chore: deploy.yml 수정 (#205)
